# -*- coding: utf-8 -*-
#error codes

OK=0				#成功(エラーなし)
NOT_SUPPORTED=1		#サポートされていない呼び出し
FILE_NOT_FOUND=2
NOT_FOUND=2
PARSING_FAILED=3
DUPLICATED=4
PEING_ERROR=5
TWITTER_ERROR=6
CANCELED=7

LOGIN_WRONG_PASSWORD=8	#ID/PW誤り
LOGIN_CONFIRM_NEEDED=9	#ユーザによる権限付与が必要
LOGIN_PEING_ERROR=10
LOGIN_TWITTER_ERROR=11
LOGIN_UNKNOWN_ERROR=12
LOGIN_RECAPTCHA_NEEDED=13


UPDATER_NEED_UPDATE = 200# アップデートが必要
UPDATER_LATEST = 204# アップデートが無い
UPDATER_VISIT_SITE = 205
UPDATER_BAD_PARAM = 400# パラメーターが不正
UPDATER_NOT_FOUND = 404# アプリケーションが存在しない

UNKNOWN=99999
